DROP TABLE IF EXISTS ROOM CASCADE;
DROP TABLE IF EXISTS PERSON CASCADE;
DROP TABLE IF EXISTS USER_ROOM CASCADE;

CREATE TABLE ROOM (
    id UUID PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
    name varchar(25)
);

CREATE TABLE PERSON (
    id UUID PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
    name varchar(25)
);

CREATE TABLE USER_ROOM (
    person_id UUID,
    room_id UUID,
    FOREIGN KEY (room_id) REFERENCES ROOM(id) ON DELETE CASCADE,
    FOREIGN KEY (person_id) REFERENCES PERSON(id) ON DELETE CASCADE,
    PRIMARY KEY(person_id, room_id)
);

